name: xeus-kernel
channels: 
  - defaults
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - jupyterlab>=3
  - ipympl
  - ipywidgets
  - ipycanvas
